### ISSUE TITLE
Background SVG looks blurry (?) in Chrome 65

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#104]

**Comment by lukaszklis** [comment]
Can confirm it occurs in Chrome 67 too.

**Comment by kotzendekrabbe** [comment]
Browser: Chrome (64,65,67)
See attached file.

Repeating pattern issue (if you remove the repeat, it's gone)

<img width="1677" alt="bildschirmfoto 2018-03-08 um 10 41 53" src="https://user-images.githubusercontent.com/731399/37144156-7e4ac66a-22bd-11e8-8e6c-baee29c49706.png">

**Comment by lukaszklis** [comment]
Played a bit in the browser and it seems like it can be fixed by not repeating the background and using `background-size: cover;` to make the SVG fill the entire container.
