### ISSUE TITLE
New page: /scholarships-guide

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#118]
- [x] create page `/scholarships-guide` (added in #119)
- [x] create content (@simonehaas)
- [x] share with all scholarship holders (@simonehaas)

**Comment by Kriesse** [comment]
@simonehaas Can you take care of creating the content?
The same page should then be created on jsconf.eu

**Comment by simonehaas** [comment]
Thank you! Will take care of the content. Olivia will help

**Comment by Kriesse** [comment]
@simonehaas This has been done and finished, thus can be closed, correct?

**Comment by Kriesse** [comment]
Done, thanks @oe @simonehaas 👍
