### ISSUE TITLE
New page: /artists

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#142]
Add a new page: `/artists`

This page should be analogue to the speakers page, 
but pull artists out of a spreadsheet

@cramforce Can you point us to where to find the data?

**Comment by Lucie-H** [comment]
@lukaszklis If you have time to do this, here is the data! https://docs.google.com/spreadsheets/d/1qgPWxuEohNuTUafleeiMbrJPecyho6GtPJBCbj-IrfM/edit?pli=1#gid=528253303

**Comment by lukaszklis** [comment]
Thanks, I’ll take care of it tonight. :)
