### ISSUE TITLE
Add a top bar navigation, with a mobile version

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#19]
@RalloTubbs we'll need this soon as we'll add more pages, so navigating is easy – right now it's inconvenient and hard to find in the footer, esp. on longer pages

**Comment by Kriesse** [comment]
@sfrdmn could you prepare the JS for this, same way as on JSconf?

**Comment by Kriesse** [comment]
related Trello ticket https://trello.com/c/0eANJq50/65-top-bar-navigation-for-cssconf-website

**Comment by lukaszklis** [comment]
Do we have the designs ready?

**Comment by Kriesse** [comment]
Related PR: https://github.com/cssconf/2018.cssconf.eu/pull/68

**Comment by Kriesse** [comment]
Done! 🎉 Thanks @lukaszklis & @verpixelt 👏
