### ISSUE TITLE
Clean up hacky layout on main page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#23]
The layout on the main page was hacked together late at night and not flexible at all – this needs to be revisited.

- [ ] make it flexible, so that we can change the copy without breaking the layout
- [ ] actually align it along the grid as planned in the mockup

**Comment by usefulthink** [comment]
I can certainly participate here, but I'm not brave enough to take it.

**Comment by Kriesse** [comment]
@usefulthink Okay, I'll clean up my own mess and will ask for help if I get desperate 👯

**Comment by Kriesse** [comment]
closing - not gonna happen - YOLO

**Comment by Kriesse** [comment]
actually it will be fixed
