### ISSUE TITLE
Schedule Page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#55]
Content similar to last year, design still needed. Use default layout until then.

https://2017.cssconf.eu/schedule/

**Comment by Kriesse** [comment]
@lukaszklis I assume we can use the speaker data spreadsheet for this too? And we would just add start time?

**Comment by lukaszklis** [comment]
Yes, I would say it would actually be start time set for a talk, not a speaker.

**Comment by Kriesse** [comment]
@RalloTubbs Is there a design yet?
We need something super simple that can go online right away, with the option to improve on later
