### ISSUE TITLE
Fix the vulnerability reported by GitHub in dependencies

### ISSUE THREAD

**Issue by lukaszklis** [cssconf/2018.cssconf.eu#73]
It can be done as soon as https://github.com/jnordberg/wintersmith/pull/332 gets merged.

**Comment by Kriesse** [comment]
Looks like it got merged, thanks @lukaszklis 🙏

**Comment by lukaszklis** [comment]
While waiting for a new release of wintersmith, we _might_ consider sticking to a specific commit version in package.json.
