### ISSUE TITLE
Add Info Page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#76]
We need a page that contains general information about the conference, the concept, values and mission, the location, accommodation and travel information, etc. The content can remain mostly the same as last year: https://2017.cssconf.eu/info/

- [x] create page
- [x] update the content (some links are not links, some details are incorrect --> needs proofread and review)
- [ ] iterate on design (add photos, map, illustrations…)

**Comment by lukaszklis** [comment]
@Kriesse is this still valid? Could you please check it with the latest version of https://2018.cssconf.eu/info/ ?

**Comment by Kriesse** [comment]
@lukaszklis Ah thanks, didn't realize the page was already there! I updated the things that are still do to above.

**Comment by Kriesse** [comment]
Closing in favor of https://github.com/cssconf/2018.cssconf.eu/issues/88
