### ISSUE TITLE
Copy: Add the venue

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#79]
We get many questions about the venue. Please review the website and see if there are any places (frontpage? info page? …) where it could be added. 

Complete address:
Arena Berlin
Eichenstraße 4
12435 Berlin 
Germany

Adding a google maps link where possible would be helpful too.

**Comment by Lucie-H** [comment]
@Kriesse Do you think we still need this ticket once it's added on the frontpage (https://github.com/cssconf/2018.cssconf.eu/pull/84) and the info page is linked there too (when https://github.com/cssconf/2018.cssconf.eu/issues/82 is done)?

**Comment by Kriesse** [comment]
@Lucie-H True, it's probably fine then. Closing!
