### ISSUE TITLE
Add Content for Scholarships

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#8]
@retrospekt @simonehaas This page must be finalized, get all necessary links, etc

**Comment by Kriesse** [comment]
blocked by https://github.com/cssconf/2018.cssconf.eu/issues/24

**Comment by Lucie-H** [comment]
@retrospekt I added the markdown files (at the moment with the content from last year), so you can work directly in there!

**Comment by Kriesse** [comment]
Done 🎉
