### ISSUE TITLE
Re-word call for speakers on front page

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2018.cssconf.eu#82]
This can go, as the CfS has passed.
It should link to the /info page instead, the copy could be something like 

> CSSconf EU 2018 is coming back to Berlin
> Get all the infos and details here

or something like that. Goal is to get people to the info page.

![image](https://user-images.githubusercontent.com/53684/35236081-09bbb55a-ff74-11e7-9bfc-35defa583d0b.png)

**Comment by Lucie-H** [comment]
@Kriesse I'll get on this as soon https://github.com/cssconf/2018.cssconf.eu/pull/85 is ready and merged.
